# Generated by Django 4.2.29 on 2026-04-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenantmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
    ]
