# Generated by Django 5.1.2 on 2026-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='ssl_txt_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='ssl_txt_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
