# Generated by Django 5.1.2 on 2026-05-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customdomain_ssl_txt_name_customdomain_ssl_txt_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='pre_validation_txt_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='pre_validation_txt_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
