# Generated by Django 5.1.2 on 2026-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customdomain_pre_validation_txt_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdomain',
            name='pre_validation_txt_name',
        ),
        migrations.RemoveField(
            model_name='customdomain',
            name='pre_validation_txt_value',
        ),
        migrations.AddField(
            model_name='customdomain',
            name='ssl_txt_name_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='ssl_txt_value_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
