# Generated by Django 5.1.2 on 2026-05-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customdomain_pre_validation_txt_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdomain',
            name='ssl_txt_name',
        ),
        migrations.RemoveField(
            model_name='customdomain',
            name='ssl_txt_name_2',
        ),
        migrations.RemoveField(
            model_name='customdomain',
            name='ssl_txt_value',
        ),
        migrations.RemoveField(
            model_name='customdomain',
            name='ssl_txt_value_2',
        ),
    ]
