# Generated by Django 5.1.2 on 2026-05-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customdomain_ssl_txt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='site_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
