# Generated by Django 5.1.2 on 2026-05-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tenant_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='blog_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('cover_image', models.CharField(blank=True, default='', max_length=500)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.CharField(blank=True, default='', max_length=500)),
                ('og_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('template', models.CharField(blank=True, choices=[('minimal', 'Minimal Reading'), ('magazine', 'Magazine'), ('cards', 'Card Grid')], default='', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='core.tenant')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='core_blogpo_tenant__254984_idx'), models.Index(fields=['tenant', 'featured'], name='core_blogpo_tenant__2074a6_idx')],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
