# Generated by Django 5.1.2 on 2026-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backfill_blogpost_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='resource_type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='secure_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/%Y/%m/'),
        ),
    ]
