# Generated by Django 5.1.2 on 2026-06-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mediaasset_bytes_mediaasset_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='core.template')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.tenant')),
            ],
            options={
                'ordering': ['nav_order', 'title'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
