# Generated by Django 5.2.15 on 2026-06-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_annotationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ghl_location_id',
            field=models.CharField(blank=True, help_text='Maps a GHL sub-account (location.id) to this tenant. When set, the /embed/ auto-login route accepts visits from that location.', max_length=64, null=True, unique=True),
        ),
    ]
