# Generated by Django 5.2.15 on 2026-06-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tenant_ghl_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=64, unique=True)),
                ('company_id', models.CharField(blank=True, default='', max_length=64)),
                ('user_type', models.CharField(choices=[('Location', 'Location'), ('Company', 'Company')], default='Location', max_length=16)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghl_installs', to='core.tenant')),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
    ]
