# Generated by Django 5.2.15 on 2026-06-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ghl_install'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdomain',
            name='cloudflare_hostname_id',
        ),
    ]
