# Generated by Django 5.2.15 on 2026-07-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_embeddableassistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlAgencyInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=64, unique=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('available_locations', models.JSONField(blank=True, default=list)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.AddField(
            model_name='ghlinstall',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ghlinstall',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], default='connected', max_length=16),
        ),
        migrations.AddField(
            model_name='ghlinstall',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_installs', to='core.ghlagencyinstall'),
        ),
    ]
