# Generated by Django 5.1.2 on 2026-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ghl_agency_install'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='source',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('mcp', 'MCP')], db_index=True, default='dashboard', max_length=16),
        ),
    ]
