# Generated by Django 5.1.2 on 2026-08-09 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contentversion_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('html_source', models.TextField()),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, default='', max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='core.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='editing_mode',
            field=models.CharField(choices=[('raw', 'Raw — not client-editable'), ('editable', 'Editable — released to the client')], default='raw', max_length=16),
        ),
        migrations.AddField(
            model_name='template',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant. NULL means the agency library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'slug'), name='uniq_template_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='uniq_library_template_slug'),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.template'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='uniq_template_version_number'),
        ),
    ]
