# Generated by Django 5.1.2 on 2026-08-18 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_backfill_template_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.page'),
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='square', max_length=40)),
                ('category', models.CharField(default='General', help_text="Palette grouping shown to the client (e.g. 'Social proof').", max_length=80)),
                ('html_source', models.TextField(help_text='Annotated fragment: one data-block/data-section wrapper.')),
                ('schema', models.JSONField(blank=True, default=dict, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'label'],
                'constraints': [models.UniqueConstraint(fields=('key',), name='uniq_blocktype_key')],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='allowed_block_types',
            field=models.ManyToManyField(blank=True, help_text="Blocks a client may insert into this template's region(s).", related_name='templates', to='core.blocktype'),
        ),
    ]
