# Generated by Django 5.1.2 on 2026-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_backfill_template_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='editing_mode',
            field=models.CharField(choices=[('raw', 'Raw (not client-editable)'), ('editable', 'Editable (released to the client)')], default='raw', max_length=16),
        ),
    ]
