# Generated by Django 5.1.2 on 2026-08-27 12:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tenant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.SlugField(max_length=80, unique=True, validators=[core.models.validate_tenant_subdomain]),
        ),
    ]
