# Generated by Django 5.1.2 on 2026-08-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_template_editing_mode'),
        ('core', '0025_alter_tenant_subdomain'),
    ]

    operations = [
    ]
