# Generated by Django 5.1.2 on 2026-09-25 17:15

from django.db import migrations, models
from django.db.models import F


def backfill_verified_at(apps, schema_editor):
    # Rows verified before CMS-65 have no stamp; their last save is the best
    # proxy, and it lets the route-syncer probe their certs once.
    CustomDomain = apps.get_model("core", "CustomDomain")
    CustomDomain.objects.filter(is_verified=True, verified_at__isnull=True).update(
        verified_at=F("updated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_blocktype_scoped_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='acme_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='acme_retried_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='acme_retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='cert_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_verified_at, migrations.RunPython.noop),
    ]
