from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    # Dispatcher — branches on request.tenant.
    path("", views.dashboard_root, name="root"),
    # Backwards-compat: old reverses to dashboard:home land on the dispatcher.
    path("home/", views.dashboard_root, name="home"),

    # ----- Agency surface (no tenant on host) ----------------------------- #
    path("templates/", views.template_list, name="template_list"),
    path("templates/new/", views.template_create, name="template_create"),
    path("templates/annotate/", views.template_annotate, name="template_annotate"),
    path("templates/annotate/status/<uuid:job_id>/", views.template_annotate_status, name="template_annotate_status"),
    path("templates/fetch-url/", views.template_fetch_url, name="template_fetch_url"),
    path("templates/<int:pk>/", views.template_detail, name="template_detail"),
    path("templates/<int:pk>/delete/", views.template_delete, name="template_delete"),

    path("sites/", views.tenant_list, name="tenant_list"),
    path("sites/new/", views.tenant_create, name="tenant_create"),
    path("sites/check-subdomain/", views.check_subdomain, name="check_subdomain"),
    path("sites/<int:pk>/", views.tenant_detail, name="tenant_detail"),
    path("sites/<int:pk>/created/", views.site_created, name="site_created"),
    # Back-compat alias — old bookmarks/redirects still resolve.
    path("sites/<int:pk>/credentials/", views.site_credentials, name="site_credentials"),
    path("sites/<int:pk>/settings/", views.tenant_settings_update, name="tenant_settings_update"),
    path("sites/<int:pk>/custom-domain/", views.tenant_custom_domain_section, name="tenant_custom_domain_section"),
    path("sites/<int:pk>/custom-domain/add/", views.tenant_custom_domain_add, name="tenant_custom_domain_add"),
    path("sites/<int:pk>/custom-domain/verify/", views.tenant_custom_domain_verify, name="tenant_custom_domain_verify"),
    path("sites/<int:pk>/custom-domain/delete/", views.tenant_custom_domain_delete, name="tenant_custom_domain_delete"),
    path("sites/<int:pk>/delete/", views.tenant_delete, name="tenant_delete"),
    path("sites/<int:pk>/members/add/", views.tenant_member_add, name="tenant_member_add"),
    path("sites/<int:pk>/members/create/", views.tenant_member_create, name="tenant_member_create"),
    path("sites/<int:pk>/members/<int:membership_id>/remove/", views.tenant_member_remove, name="tenant_member_remove"),
    path("sites/<int:pk>/members/<int:membership_id>/role/", views.tenant_member_role, name="tenant_member_role"),
    path("sites/<int:pk>/site-settings/", views.tenant_site_settings, name="tenant_site_settings"),
    path("sites/<int:pk>/blog/", views.blog_list, name="blog_list"),
    path("sites/<int:pk>/blog/new/", views.blog_create, name="blog_create"),
    path("sites/<int:pk>/blog/reorder/", views.blog_reorder, name="blog_reorder"),
    path("sites/<int:pk>/blog/settings/", views.blog_settings, name="blog_settings"),
    path("sites/<int:pk>/blog/sanitize/", views.blog_sanitize, name="blog_sanitize"),
    path("sites/<int:pk>/blog/strip-preview/", views.blog_strip_preview, name="blog_strip_preview"),
    path("sites/<int:pk>/blog/preview/new/", views.blog_preview_new, name="blog_preview_new"),
    path("sites/<int:pk>/blog/<int:post_pk>/", views.blog_edit, name="blog_edit"),
    path("sites/<int:pk>/blog/<int:post_pk>/delete/", views.blog_delete, name="blog_delete"),
    path("sites/<int:pk>/blog/<int:post_pk>/featured/", views.blog_featured_toggle, name="blog_featured_toggle"),
    path("sites/<int:pk>/blog/<int:post_pk>/preview/", views.blog_preview, name="blog_preview"),
    path("sites/<int:pk>/pages/", views.page_list, name="page_list"),
    path("sites/<int:pk>/pages/new/", views.page_create, name="page_create"),
    path("sites/<int:pk>/pages/<int:page_pk>/edit/", views.page_editor, name="page_editor"),
    path("sites/<int:pk>/pages/<int:page_pk>/preview/", views.page_preview, name="page_preview"),
    path("sites/<int:pk>/pages/<int:page_pk>/save/", views.page_save, name="page_save"),
    path("sites/<int:pk>/pages/<int:page_pk>/publish/", views.page_publish, name="page_publish"),
    path("sites/<int:pk>/pages/<int:page_pk>/delete/", views.page_delete, name="page_delete"),
    path("sites/<int:pk>/edit/", views.tenant_editor, name="tenant_editor"),
    path("sites/<int:pk>/preview/", views.tenant_preview, name="tenant_preview"),
    path("sites/<int:pk>/save/", views.tenant_save, name="tenant_save"),
    path("sites/<int:pk>/publish/", views.tenant_publish, name="tenant_publish"),
    path("sites/<int:pk>/upload/", views.tenant_upload, name="tenant_upload"),
    path("sites/<int:pk>/video-sign/", views.tenant_video_sign, name="tenant_video_sign"),
    path("sites/<int:pk>/video-confirm/", views.tenant_video_confirm, name="tenant_video_confirm"),
    path("sites/<int:pk>/versions/", views.tenant_versions, name="tenant_versions"),
    path("sites/<int:pk>/versions/restore/", views.tenant_version_restore, name="tenant_version_restore"),
    path("sites/<int:pk>/versions/<int:version_id>/preview/", views.tenant_version_preview, name="tenant_version_preview"),

    path("custom-domains/", views.custom_domain_list, name="custom_domain_list"),
    path("custom-domains/<int:pk>/force-verify/", views.custom_domain_force_verify, name="custom_domain_force_verify"),
    path("custom-domains/<int:pk>/force-delete/", views.custom_domain_force_delete_local, name="custom_domain_force_delete_local"),

    path("users/", views.user_list, name="user_list"),
    path("users/new/", views.user_create, name="user_create"),
    path("users/<int:pk>/", views.user_detail, name="user_detail"),
    path("users/<int:pk>/credentials/", views.user_credentials, name="user_credentials"),
    path("users/<int:pk>/create-login/", views.user_create_login, name="user_create_login"),
    path("users/<int:pk>/reset-password/", views.user_reset_password, name="user_reset_password"),
    path("users/<int:pk>/deactivate/", views.user_deactivate, name="user_deactivate"),
    path("users/<int:pk>/activate/", views.user_activate, name="user_activate"),
    path("users/<int:pk>/make-staff/", views.user_make_staff, name="user_make_staff"),
    path("users/<int:pk>/memberships/<int:membership_id>/remove/", views.user_remove_membership, name="user_remove_membership"),

    # ----- Tenant surface (host resolves to a tenant) --------------------- #
    path("editor/", views.tenant_home, name="tenant_home"),
    path("editor/preview/", views.tenant_preview_self, name="tenant_preview_self"),
    path("editor/save/", views.tenant_save_self, name="tenant_save_self"),
    path("editor/publish/", views.tenant_publish_self, name="tenant_publish_self"),
    path("editor/upload/", views.tenant_upload_self, name="tenant_upload_self"),
    path("editor/video-sign/", views.tenant_video_sign_self, name="tenant_video_sign_self"),
    path("editor/video-confirm/", views.tenant_video_confirm_self, name="tenant_video_confirm_self"),
    path("editor/versions/", views.tenant_versions_self, name="tenant_versions_self"),
    path("editor/versions/restore/", views.tenant_version_restore_self, name="tenant_version_restore_self"),
    path("editor/versions/<int:version_id>/preview/", views.tenant_version_preview_self, name="tenant_version_preview_self"),
    path("editor/settings/", views.tenant_site_settings_self, name="tenant_site_settings_self"),

    path("team/", views.team_self, name="team_self"),
    path("team/create/", views.team_member_create_self, name="team_member_create_self"),
    path("team/credentials/", views.team_credentials_self, name="team_credentials_self"),
    path("team/<int:membership_id>/remove/", views.team_member_remove_self, name="team_member_remove_self"),
    path("team/<int:membership_id>/role/", views.team_member_role_self, name="team_member_role_self"),

    path("pages/", views.page_list_self, name="page_list_self"),
    path("pages/new/", views.page_create_self, name="page_create_self"),
    path("pages/<int:page_pk>/edit/", views.page_editor_self, name="page_editor_self"),
    path("pages/<int:page_pk>/preview/", views.page_preview_self, name="page_preview_self"),
    path("pages/<int:page_pk>/save/", views.page_save_self, name="page_save_self"),
    path("pages/<int:page_pk>/publish/", views.page_publish_self, name="page_publish_self"),
    path("pages/<int:page_pk>/delete/", views.page_delete_self, name="page_delete_self"),

    path("blog/", views.blog_list_self, name="blog_list_self"),
    path("blog/new/", views.blog_create_self, name="blog_create_self"),
    path("blog/reorder/", views.blog_reorder_self, name="blog_reorder_self"),
    path("blog/settings/", views.blog_settings_self, name="blog_settings_self"),
    path("blog/sanitize/", views.blog_sanitize_self, name="blog_sanitize_self"),
    path("blog/strip-preview/", views.blog_strip_preview_self, name="blog_strip_preview_self"),
    path("blog/preview/new/", views.blog_preview_new_self, name="blog_preview_new_self"),
    path("blog/<int:post_pk>/", views.blog_edit_self, name="blog_edit_self"),
    path("blog/<int:post_pk>/delete/", views.blog_delete_self, name="blog_delete_self"),
    path("blog/<int:post_pk>/featured/", views.blog_featured_toggle_self, name="blog_featured_toggle_self"),
    path("blog/<int:post_pk>/preview/", views.blog_preview_self, name="blog_preview_self"),
]
