import json

from django.contrib.auth import get_user_model
from django.test import Client, TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from core.models import Template, Tenant, TenantMembership, BlogPost
from core.services.sanitizer import sanitize_html


HOME_HTML = (
    "<!doctype html><html><head><title>Home</title></head><body>"
    "<h1 data-edit='hero.title' data-type='text'>Hi</h1>"
    "<footer data-section='footer'><p>foot</p></footer>"
    "</body></html>"
)


def _make_template():
    return Template.objects.create(name="Home tpl", html_source=HOME_HTML)


def _post(tenant, title, *, status=BlogPost.STATUS_PUBLISHED, featured=False, order=0, **kw):
    return BlogPost.objects.create(
        tenant=tenant,
        title=title,
        status=status,
        publish_date=timezone.now() if status == BlogPost.STATUS_PUBLISHED else None,
        featured=featured,
        featured_order=order,
        **kw,
    )


# --------------------------------------------------------------------------- #
# Sanitizer                                                                     #
# --------------------------------------------------------------------------- #


class SanitizerTests(TestCase):
    def test_strips_script(self):
        self.assertNotIn("<script", sanitize_html("<p>ok</p><script>alert(1)</script>"))

    def test_strips_event_handlers(self):
        out = sanitize_html('<img src="https://x/a.png" onerror="alert(1)">')
        self.assertNotIn("onerror", out)

    def test_drops_javascript_href(self):
        out = sanitize_html('<a href="javascript:alert(1)">x</a>')
        self.assertNotIn("javascript", out)
        self.assertIn(">x</a>", out)

    def test_external_link_gets_rel(self):
        out = sanitize_html('<a href="https://example.com">e</a>')
        self.assertIn('rel="noopener noreferrer"', out)
        self.assertIn('target="_blank"', out)

    def test_keeps_allowed_tags(self):
        out = sanitize_html("<h2>H</h2><blockquote>q</blockquote><ul><li>a</li></ul>")
        self.assertIn("<h2>", out)
        self.assertIn("<blockquote>", out)
        self.assertIn("<li>", out)

    def test_unwraps_unknown_tag_keeping_text(self):
        out = sanitize_html('<div onclick="x()">keep</div>')
        self.assertNotIn("<div", out)
        self.assertIn("keep", out)

    def test_drops_style_and_class(self):
        out = sanitize_html('<p style="x" class="y">t</p>')
        self.assertNotIn("style=", out)
        self.assertNotIn("class=", out)


# --------------------------------------------------------------------------- #
# Model                                                                         #
# --------------------------------------------------------------------------- #


@override_settings(TENANT_BASE_DOMAIN="localhost")
class BlogModelTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        User = get_user_model()
        cls.staff = User.objects.create_user("agency", password="x", is_staff=True)
        tpl = _make_template()
        cls.t1 = Tenant.objects.create(name="Acme", subdomain="acme", template=tpl, owner=cls.staff)
        cls.t2 = Tenant.objects.create(name="Beta", subdomain="beta", template=tpl, owner=cls.staff)

    def test_slug_autogenerated(self):
        p = _post(self.t1, "Hello World")
        self.assertEqual(p.slug, "hello-world")

    def test_slug_unique_within_tenant(self):
        _post(self.t1, "Hello World")
        p2 = _post(self.t1, "Hello World")
        self.assertEqual(p2.slug, "hello-world-2")

    def test_same_slug_across_tenants_ok(self):
        a = _post(self.t1, "Shared")
        b = _post(self.t2, "Shared")
        self.assertEqual(a.slug, b.slug)

    def test_display_excerpt_from_body(self):
        p = _post(self.t1, "T", body="<p>Hello there friend</p>", excerpt="")
        self.assertEqual(p.display_excerpt(), "Hello there friend")

    def test_resolved_seo_layers_over_site(self):
        p = _post(self.t1, "Title", seo_title="", seo_description="Desc", cover_image="https://c/x.png")
        seo = p.resolved_seo({"ga_measurement_id": "G-1", "page_title": "site"})
        self.assertEqual(seo["page_title"], "Title")  # falls back to title
        self.assertEqual(seo["meta_description"], "Desc")
        self.assertEqual(seo["og_image_url"], "https://c/x.png")
        self.assertEqual(seo["ga_measurement_id"], "G-1")  # site value preserved

    # --- publish_date invariant (regression: undated published posts were
    #     invisible to the strip / public queries) ---------------------------
    def test_published_post_gets_publish_date_on_save(self):
        # Mirrors admin / seed / non-form creation: no explicit publish_date.
        p = BlogPost.objects.create(
            tenant=self.t1, title="No Date", status=BlogPost.STATUS_PUBLISHED,
        )
        self.assertIsNotNone(p.publish_date)  # stamped by save()

    def test_explicit_publish_date_preserved(self):
        future = timezone.now() + timezone.timedelta(days=7)
        p = BlogPost.objects.create(
            tenant=self.t1, title="Scheduled",
            status=BlogPost.STATUS_PUBLISHED, publish_date=future,
        )
        self.assertEqual(p.publish_date, future)  # scheduled date not overwritten

    def test_draft_does_not_get_publish_date(self):
        p = BlogPost.objects.create(
            tenant=self.t1, title="Draft", status=BlogPost.STATUS_DRAFT,
        )
        self.assertIsNone(p.publish_date)

    def test_featured_published_without_explicit_date_appears_in_strip(self):
        from core.services import blog_render
        BlogPost.objects.create(
            tenant=self.t1, title="Ghost Buster",
            status=BlogPost.STATUS_PUBLISHED, featured=True,
        )
        names = [p.title for p in blog_render.featured_posts(self.t1, 6)]
        self.assertIn("Ghost Buster", names)

    def test_published_future_dated_post_is_visible(self):
        # The actual production bug: a Published+Featured post whose
        # publish_date sits in the future (the timezone-naive datetime-local
        # input stores a client's local "now" as a few hours ahead in UTC) was
        # excluded by the old `publish_date <= now` gate. Status governs
        # visibility now, so it must appear.
        from core.services import blog_render
        future = timezone.now() + timezone.timedelta(hours=6)
        BlogPost.objects.create(
            tenant=self.t1, title="Posted A Bit Early",
            status=BlogPost.STATUS_PUBLISHED, featured=True, publish_date=future,
        )
        names = [p.title for p in blog_render.featured_posts(self.t1, 6)]
        self.assertIn("Posted A Bit Early", names)
        # ...and a draft with a past date is still hidden (status gate intact).
        BlogPost.objects.create(
            tenant=self.t1, title="Still Draft", status=BlogPost.STATUS_DRAFT,
            featured=True, publish_date=timezone.now() - timezone.timedelta(days=1),
        )
        names = [p.title for p in blog_render.featured_posts(self.t1, 6)]
        self.assertNotIn("Still Draft", names)


# --------------------------------------------------------------------------- #
# Public surfaces                                                               #
# --------------------------------------------------------------------------- #


@override_settings(TENANT_BASE_DOMAIN="localhost")
class BlogPublicTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        User = get_user_model()
        cls.staff = User.objects.create_user("agency", password="x", is_staff=True)
        cls.member = User.objects.create_user("alice", password="x")
        tpl = _make_template()
        cls.tenant = Tenant.objects.create(
            name="Acme", subdomain="acme", template=tpl, owner=cls.staff, is_published=True,
        )
        TenantMembership.objects.create(tenant=cls.tenant, user=cls.member)
        cls.other = Tenant.objects.create(
            name="Beta", subdomain="beta", template=tpl, owner=cls.staff, is_published=True,
        )
        cls.pub = _post(cls.tenant, "Live Post", body="<p>hi</p><script>x</script>")
        cls.draft = _post(cls.tenant, "Secret Draft", status=BlogPost.STATUS_DRAFT)
        _post(cls.other, "Beta Only")

    def _anon(self):
        return Client(HTTP_HOST="acme.localhost")

    def test_index_lists_published(self):
        r = self._anon().get("/blog/")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "Live Post")
        self.assertNotContains(r, "Secret Draft")

    def test_index_excludes_other_tenant(self):
        r = self._anon().get("/blog/")
        self.assertNotContains(r, "Beta Only")

    def test_detail_published_ok_and_sanitized(self):
        r = self._anon().get(f"/blog/{self.pub.slug}/")
        self.assertEqual(r.status_code, 200)
        self.assertNotIn(b"<script>x", r.content)

    def test_detail_draft_404_for_anon(self):
        r = self._anon().get(f"/blog/{self.draft.slug}/")
        self.assertEqual(r.status_code, 404)

    def test_detail_draft_visible_to_member(self):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(self.member)
        r = c.get(f"/blog/{self.draft.slug}/")
        self.assertEqual(r.status_code, 200)

    def test_detail_injects_seo_title(self):
        self.pub.seo_title = "Custom SEO"
        self.pub.save()
        r = self._anon().get(f"/blog/{self.pub.slug}/")
        self.assertContains(r, "<title>Custom SEO</title>")

    def test_unpublished_site_blog_404(self):
        self.tenant.is_published = False
        self.tenant.save(update_fields=["is_published"])
        r = self._anon().get("/blog/")
        self.assertEqual(r.status_code, 404)

    def test_fallback_path_route(self):
        r = Client(HTTP_HOST="localhost").get(f"/site/acme/blog/")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "Live Post")

    def test_detail_renders_when_footer_nested_in_content_section(self):
        # Regression: a plain <footer> (no data-section) nested INSIDE a content
        # section used to be destroyed when that section was decomposed, leaving
        # it detached so footer.insert_before() raised "Element has no parent"
        # (production 500 on /blog/.../ and the editor preview). Now the chrome
        # is rescued before decomposition.
        nested_footer_html = (
            "<!doctype html><html><head><title>Home</title></head><body>"
            "<h1 data-edit='hero.title' data-type='text'>Hi</h1>"
            "<section data-section='contact'><p>Reach us</p>"
            "<footer><p>nested foot</p></footer></section>"
            "</body></html>"
        )
        tpl = Template.objects.create(name="Nested footer", html_source=nested_footer_html)
        tenant = Tenant.objects.create(
            name="Nest", subdomain="nest", template=tpl, owner=self.staff, is_published=True,
        )
        post = _post(tenant, "Nested Footer Post", body="<p>body</p>")
        r = Client(HTTP_HOST="nest.localhost").get(f"/blog/{post.slug}/")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "nested foot")  # footer survived, not dropped


# --------------------------------------------------------------------------- #
# Homepage strip                                                                #
# --------------------------------------------------------------------------- #


@override_settings(TENANT_BASE_DOMAIN="localhost")
class BlogStripTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        User = get_user_model()
        cls.staff = User.objects.create_user("agency", password="x", is_staff=True)
        cls.tpl = _make_template()
        cls.tenant = Tenant.objects.create(
            name="Acme", subdomain="acme", template=cls.tpl, owner=cls.staff, is_published=True,
            blog_settings={"template": "cards", "strip_count": 2, "strip_enabled": True},
        )

    def test_strip_absent_without_featured(self):
        r = Client(HTTP_HOST="acme.localhost").get("/")
        self.assertNotIn(b"cms-blog-strip", r.content)

    def test_strip_present_and_ordered(self):
        _post(self.tenant, "First", featured=True, order=1)
        _post(self.tenant, "Second", featured=True, order=0)
        _post(self.tenant, "Third", featured=True, order=2)
        r = Client(HTTP_HOST="acme.localhost").get("/")
        body = r.content.decode()
        self.assertIn("cms-blog-strip", body)
        # strip_count=2 → only first two by order (Second, First); Third excluded
        self.assertIn("Second", body)
        self.assertIn("First", body)
        self.assertNotIn("Third", body)
        self.assertLess(body.index("Second"), body.index("First"))

    def test_strip_excludes_draft_featured(self):
        _post(self.tenant, "DraftFeat", status=BlogPost.STATUS_DRAFT, featured=True, order=0)
        r = Client(HTTP_HOST="acme.localhost").get("/")
        self.assertNotIn(b"cms-blog-strip", r.content)

    def test_strip_marker_injection(self):
        self.tpl.html_source = (
            "<!doctype html><html><head><title>H</title></head><body>"
            "<div data-blog-strip></div><footer data-section='footer'></footer>"
            "</body></html>"
        )
        self.tpl.save()
        _post(self.tenant, "MarkedPost", featured=True, order=0)
        r = Client(HTTP_HOST="acme.localhost").get("/")
        self.assertContains(r, "MarkedPost")
        self.assertContains(r, "cms-blog-strip")


# --------------------------------------------------------------------------- #
# Site chrome wrapping (blog pages render inside the client's navbar/footer)    #
# --------------------------------------------------------------------------- #

# A template with a real navbar, a homepage content section, and a footer.
CHROME_HTML = (
    "<!doctype html><html><head><title>Home</title>"
    "<style>.site-token{color:#abc123;} "
    ".wrap{max-width:1000px;margin:0 auto;padding:0 40px;} "
    ".hero{background:#112233;color:#fff;}</style></head><body>"
    "<nav data-section='nav'><div class='wrap'>"
    "<a class='brand' href='#'>BRAND NAV</a>"
    "<a href='#about'>About</a>"
    "<a href='/contact'>Contact</a>"
    "<a href='mailto:hi@x.com'>Mail</a>"
    "<a href='https://ext.example'>Ext</a>"
    "</div></nav>"
    "<section class='hero' data-section='hero'>"
    "<h1 data-edit='hero.title' data-type='text'>BRAND HERO HEADLINE</h1>"
    "<script>window.__hero_section_script=1;</script>"
    "</section>"
    "<footer data-section='footer'><p>BRAND FOOTER</p><a href='#programs'>Programs</a></footer>"
    "<script>window.__chrome_ready=true;</script>"
    "</body></html>"
)


@override_settings(TENANT_BASE_DOMAIN="localhost")
class BlogChromeTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        User = get_user_model()
        cls.staff = User.objects.create_user("agency", password="x", is_staff=True)
        cls.acme_tpl = Template.objects.create(name="Acme tpl", html_source=CHROME_HTML.replace("BRAND", "ACME"))
        cls.beta_tpl = Template.objects.create(name="Beta tpl", html_source=CHROME_HTML.replace("BRAND", "BETA"))
        cls.acme = Tenant.objects.create(
            name="Acme", subdomain="acme", template=cls.acme_tpl, owner=cls.staff, is_published=True,
        )
        cls.beta = Tenant.objects.create(
            name="Beta", subdomain="beta", template=cls.beta_tpl, owner=cls.staff, is_published=True,
        )
        cls.post = _post(cls.acme, "Wrapped Post", body="<p>hello world</p>")
        _post(cls.beta, "Beta Post")

    def _get(self, host, path):
        return Client(HTTP_HOST=host).get(path)

    def test_index_wrapped_in_site_chrome(self):
        r = self._get("acme.localhost", "/blog/")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "ACME NAV")        # site navbar present
        self.assertContains(r, "ACME FOOTER")     # site footer present
        self.assertContains(r, "site-token")      # site global CSS present
        self.assertContains(r, "Wrapped Post")    # blog content present
        self.assertNotContains(r, "HERO HEADLINE")  # homepage section removed

    def test_detail_wrapped_in_site_chrome(self):
        r = self._get("acme.localhost", f"/blog/{self.post.slug}/")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "ACME NAV")
        self.assertContains(r, "ACME FOOTER")
        self.assertContains(r, "cms-blog")          # scoped blog wrapper
        self.assertContains(r, "hello world")       # post body
        self.assertNotContains(r, "HERO HEADLINE")

    def test_each_client_gets_its_own_chrome(self):
        r = self._get("beta.localhost", "/blog/")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "BETA NAV")
        self.assertNotContains(r, "ACME NAV")

    def test_detail_seo_title_in_wrapped_head(self):
        self.post.seo_title = "Wrapped SEO"
        self.post.save()
        r = self._get("acme.localhost", f"/blog/{self.post.slug}/")
        self.assertContains(r, "<title>Wrapped SEO</title>")

    def test_single_document_not_nested_html(self):
        # The wrapped output must be ONE document, not a blog doc nested in
        # the site doc (which would mean the fragment refactor regressed).
        r = self._get("acme.localhost", f"/blog/{self.post.slug}/")
        self.assertEqual(r.content.decode().lower().count("<body"), 1)

    def test_no_leaked_template_comment_syntax(self):
        # Regression: a multi-line {# #} comment leaked into the page as text.
        # Rendered blog HTML must never contain Django comment-hash syntax.
        for path in ("/blog/", f"/blog/{self.post.slug}/"):
            body = self._get("acme.localhost", path).content.decode()
            self.assertNotIn("{#", body, path)
            self.assertNotIn("#}", body, path)
            self.assertNotIn("CONTENT fragment", body, path)  # the comment text

    def test_chrome_offset_script_present(self):
        # The fixed/absolute-navbar offset logic ships (inlined) on blog pages.
        for path in ("/blog/", f"/blog/{self.post.slug}/"):
            r = self._get("acme.localhost", path)
            self.assertContains(r, "nav.offsetHeight")  # marker from the offset script

    def test_blog_stylesheet_survives_wrapping(self):
        # Regression: lxml hoisted the fragment's leading <style> into its
        # <head>, so wrap_in_site_chrome dropped the entire blog stylesheet and
        # the content rendered unstyled. The scoped CSS must be in the output.
        for path in ("/blog/", f"/blog/{self.post.slug}/"):
            body = self._get("acme.localhost", path).content.decode()
            self.assertIn(".cms-blog", body)
            self.assertIn(".blog-prose", body)      # typography rules present
            self.assertIn("blog-wrap", body)        # container rule present

    def test_container_detected_and_applied(self):
        # The blog wrapper should carry the site's detected container width +
        # gutter so it lines up with the navbar (test template uses 1000/40).
        body = self._get("acme.localhost", f"/blog/{self.post.slug}/").content.decode()
        self.assertIn("--site-cw: 1000px", body)
        self.assertIn("--site-gut: 40px", body)

    def test_blog_css_is_fully_scoped(self):
        # Regression for the navbar-fade leak: every selector the blog emits
        # must be scoped under .cms-blog (or :root / @-rules), so nothing can
        # restyle the client's navbar/footer/chrome.
        from bs4 import BeautifulSoup
        body = self._get("acme.localhost", f"/blog/{self.post.slug}/").content.decode()
        soup = BeautifulSoup(body, "lxml")
        leaked = []
        for st in soup.find_all("style"):
            css = st.string or ""
            if ".cms-blog" not in css:
                continue  # client's own stylesheet — leave it alone
            for rule in css.split("}"):
                if "{" not in rule:
                    continue
                sel = rule.split("{")[0].strip()
                if not sel or sel.startswith("@") or sel.startswith("/*"):
                    continue
                for part in sel.split(","):
                    p = part.strip()
                    if p and ".cms-blog" not in p and ":root" not in p:
                        leaked.append(p)
        self.assertEqual(leaked, [], "blog CSS leaked unscoped selectors: %s" % leaked)

    def test_navbar_masthead_backdrop_applied(self):
        # The client's hero background is reproduced behind the (transparent,
        # light-text) navbar so it stays readable on blog pages.
        body = self._get("acme.localhost", f"/blog/{self.post.slug}/").content.decode()
        self.assertIn("--cms-masthead: #112233", body)
        self.assertIn(".cms-blog::before", body)  # the backdrop band

    # --- chrome interactivity: anchor links + scripts ----------------------
    def test_chrome_anchor_links_rewritten_on_blog(self):
        body = self._get("acme.localhost", f"/blog/{self.post.slug}/").content.decode()
        self.assertIn('href="/#about"', body)       # nav anchor → homepage
        self.assertIn('href="/#programs"', body)    # footer anchor too

    def test_chrome_non_anchor_and_bare_hash_untouched(self):
        body = self._get("acme.localhost", f"/blog/{self.post.slug}/").content.decode()
        self.assertIn('href="#"', body)             # bare # (logo / JS) kept
        self.assertNotIn('href="/#"', body)         # ...not rewritten
        self.assertIn('href="/contact"', body)      # absolute path kept
        self.assertIn('href="mailto:hi@x.com"', body)
        self.assertIn('href="https://ext.example"', body)

    def test_homepage_anchors_not_rewritten(self):
        body = self._get("acme.localhost", "/").content.decode()
        self.assertIn('href="#about"', body)        # homepage keeps in-page anchors
        self.assertNotIn('href="/#about"', body)

    def test_agency_fallback_anchor_prefix(self):
        body = self._get("localhost", f"/site/acme/blog/{self.post.slug}/").content.decode()
        self.assertIn('href="/site/acme/#about"', body)

    def test_chrome_scripts_present_on_blog(self):
        body = self._get("acme.localhost", f"/blog/{self.post.slug}/").content.decode()
        self.assertIn("window.__chrome_ready", body)         # body-level site script
        self.assertIn("window.__hero_section_script", body)  # rescued from removed section


# --------------------------------------------------------------------------- #
# Dashboard CRUD + auth                                                         #
# --------------------------------------------------------------------------- #


@override_settings(
    TENANT_BASE_DOMAIN="localhost",
    STORAGES={
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    },
)
class BlogDashboardTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        User = get_user_model()
        cls.staff = User.objects.create_user("agency", password="x", is_staff=True)
        cls.member = User.objects.create_user("alice", password="x")
        cls.outsider = User.objects.create_user("eve", password="x")
        tpl = _make_template()
        cls.tenant = Tenant.objects.create(
            name="Acme", subdomain="acme", template=tpl, owner=cls.staff, is_published=True,
        )
        TenantMembership.objects.create(tenant=cls.tenant, user=cls.member)

    def _agency(self):
        c = Client(HTTP_HOST="localhost")
        c.force_login(self.staff)
        return c

    def _tenant(self, user=None):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(user or self.member)
        return c

    # auth
    def test_outsider_blocked_tenant_blog(self):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(self.outsider)
        self.assertEqual(c.get(reverse("dashboard:blog_list_self")).status_code, 403)

    def test_member_sees_blog_list(self):
        self.assertEqual(self._tenant().get(reverse("dashboard:blog_list_self")).status_code, 200)

    def test_staff_sees_agency_blog_list(self):
        r = self._agency().get(reverse("dashboard:blog_list", args=[self.tenant.pk]))
        self.assertEqual(r.status_code, 200)

    def test_non_staff_blocked_agency_blog(self):
        c = Client(HTTP_HOST="localhost")
        c.force_login(self.member)
        r = c.get(reverse("dashboard:blog_list", args=[self.tenant.pk]))
        self.assertEqual(r.status_code, 403)

    # create
    def test_create_post_published_sets_publish_date(self):
        c = self._tenant()
        r = c.post(reverse("dashboard:blog_create_self"), {
            "title": "My First Post",
            "body": "<p>Body</p><script>bad</script>",
            "status": "published",
        })
        self.assertEqual(r.status_code, 302)
        post = BlogPost.objects.get(tenant=self.tenant, title="My First Post")
        self.assertEqual(post.slug, "my-first-post")
        self.assertIsNotNone(post.publish_date)
        self.assertNotIn("<script", post.body)  # sanitized on save

    def test_create_via_agency_scoped(self):
        c = self._agency()
        r = c.post(reverse("dashboard:blog_create", args=[self.tenant.pk]), {
            "title": "Agency Post", "body": "<p>x</p>", "status": "draft",
        })
        self.assertEqual(r.status_code, 302)
        self.assertTrue(BlogPost.objects.filter(tenant=self.tenant, title="Agency Post").exists())

    # edit
    def test_edit_updates_post(self):
        p = _post(self.tenant, "Old", status=BlogPost.STATUS_DRAFT)
        c = self._tenant()
        r = c.post(reverse("dashboard:blog_edit_self", args=[p.pk]), {
            "title": "New Title", "body": "<p>z</p>", "status": "draft", "slug": p.slug,
        })
        self.assertEqual(r.status_code, 302)
        p.refresh_from_db()
        self.assertEqual(p.title, "New Title")

    # delete
    def test_delete_post(self):
        p = _post(self.tenant, "Doomed")
        c = self._tenant()
        r = c.post(reverse("dashboard:blog_delete_self", args=[p.pk]))
        self.assertEqual(r.status_code, 302)
        self.assertFalse(BlogPost.objects.filter(pk=p.pk).exists())

    # featured toggle
    def test_featured_toggle(self):
        p = _post(self.tenant, "P")
        c = self._tenant()
        c.post(reverse("dashboard:blog_featured_toggle_self", args=[p.pk]))
        p.refresh_from_db()
        self.assertTrue(p.featured)
        c.post(reverse("dashboard:blog_featured_toggle_self", args=[p.pk]))
        p.refresh_from_db()
        self.assertFalse(p.featured)

    # reorder
    def test_reorder_persists(self):
        a = _post(self.tenant, "A", featured=True, order=0)
        b = _post(self.tenant, "B", featured=True, order=1)
        c = self._tenant()
        r = c.post(
            reverse("dashboard:blog_reorder_self"),
            data=json.dumps({"order": [b.pk, a.pk]}),
            content_type="application/json",
        )
        self.assertEqual(r.status_code, 200)
        a.refresh_from_db(); b.refresh_from_db()
        self.assertEqual(b.featured_order, 0)
        self.assertEqual(a.featured_order, 1)

    # settings
    def test_settings_save_clamps_count(self):
        c = self._tenant()
        c.post(reverse("dashboard:blog_settings_self"), {
            "template": "magazine", "title": "News", "strip_heading": "Latest",
            "strip_count": "99", "strip_enabled": "on",
        })
        self.tenant.refresh_from_db()
        self.assertEqual(self.tenant.blog_settings["template"], "magazine")
        self.assertEqual(self.tenant.blog_settings["strip_count"], 6)  # clamped to max
        self.assertTrue(self.tenant.blog_settings["strip_enabled"])

    def test_settings_rejects_bad_template(self):
        c = self._tenant()
        c.post(reverse("dashboard:blog_settings_self"), {
            "template": "nope", "title": "B", "strip_count": "3",
        })
        self.tenant.refresh_from_db()
        self.assertIn(self.tenant.blog_settings["template"], {"minimal", "magazine", "cards"})

    def test_cross_tenant_post_not_editable(self):
        other = Tenant.objects.create(
            name="Beta", subdomain="beta",
            template=self.tenant.template, owner=self.staff,
        )
        foreign = _post(other, "Foreign")
        c = self._tenant()  # acme member
        r = c.get(reverse("dashboard:blog_edit_self", args=[foreign.pk]))
        self.assertEqual(r.status_code, 404)


# --------------------------------------------------------------------------- #
# Live preview (editor iframe bridge, body sanitize, strip preview)            #
# --------------------------------------------------------------------------- #


@override_settings(
    TENANT_BASE_DOMAIN="localhost",
    STORAGES={
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    },
)
class BlogPreviewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        User = get_user_model()
        cls.staff = User.objects.create_user("agency", password="x", is_staff=True)
        cls.member = User.objects.create_user("alice", password="x")
        cls.outsider = User.objects.create_user("eve", password="x")
        tpl = _make_template()
        cls.tenant = Tenant.objects.create(
            name="Acme", subdomain="acme", template=tpl, owner=cls.staff, is_published=True,
        )
        TenantMembership.objects.create(tenant=cls.tenant, user=cls.member)

    def _agency(self):
        c = Client(HTTP_HOST="localhost")
        c.force_login(self.staff)
        return c

    def _tenant(self, user=None):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(user or self.member)
        return c

    # --- the regression that motivated this work: editor pages must load ---
    def test_blog_list_renders_no_reverse_error(self):
        # Previously raised NoReverseMatch (blog_preview routes unwired).
        self.assertEqual(self._tenant().get(reverse("dashboard:blog_list_self")).status_code, 200)

    def test_new_post_form_renders(self):
        self.assertEqual(self._tenant().get(reverse("dashboard:blog_create_self")).status_code, 200)

    # --- preview route renders the bridge, saved + unsaved, both surfaces ---
    def test_preview_new_has_bridge_script(self):
        r = self._tenant().get(reverse("dashboard:blog_preview_new_self"))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "blog_preview.js")

    def test_preview_saved_post_tenant(self):
        p = _post(self.tenant, "Hello", status=BlogPost.STATUS_DRAFT)
        r = self._tenant().get(reverse("dashboard:blog_preview_self", args=[p.pk]))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "Hello")
        self.assertContains(r, 'data-blog-edit="body"')

    def test_preview_saved_post_agency(self):
        p = _post(self.tenant, "Agency Preview", status=BlogPost.STATUS_DRAFT)
        r = self._agency().get(reverse("dashboard:blog_preview", args=[self.tenant.pk, p.pk]))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "Agency Preview")

    def test_preview_style_override(self):
        p = _post(self.tenant, "Styled", status=BlogPost.STATUS_DRAFT)
        url = reverse("dashboard:blog_preview_self", args=[p.pk])
        r = self._tenant().get(url + "?style=magazine")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "blog--magazine")

    def test_preview_marks_author_and_date_editable(self):
        p = _post(self.tenant, "WithMeta", status=BlogPost.STATUS_DRAFT, author="Jo")
        r = self._tenant().get(reverse("dashboard:blog_preview_self", args=[p.pk]))
        self.assertContains(r, 'data-blog-edit="author"')
        self.assertContains(r, 'data-blog-edit="publish_date"')

    def test_preview_auth_gated(self):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(self.outsider)
        self.assertEqual(c.get(reverse("dashboard:blog_preview_new_self")).status_code, 403)

    # --- body sanitize round-trip mirrors the public sanitizer -------------
    def test_sanitize_strips_dangerous_html(self):
        c = self._tenant()
        payload = '<p>Hi</p><script>alert(1)</script><img src=x onerror="bad()">'
        r = c.post(reverse("dashboard:blog_sanitize_self"), {"body": payload})
        self.assertEqual(r.status_code, 200)
        out = r.json()["html"]
        self.assertEqual(out, sanitize_html(payload))  # single source of truth
        self.assertNotIn("<script", out)
        self.assertNotIn("onerror", out)

    def test_sanitize_agency_surface(self):
        c = self._agency()
        r = c.post(reverse("dashboard:blog_sanitize", args=[self.tenant.pk]), {"body": "<p>ok</p>"})
        self.assertEqual(r.status_code, 200)
        self.assertIn("<p>ok</p>", r.json()["html"])

    def test_sanitize_requires_post(self):
        self.assertEqual(self._tenant().get(reverse("dashboard:blog_sanitize_self")).status_code, 405)

    def test_sanitize_auth_gated(self):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(self.outsider)
        r = c.post(reverse("dashboard:blog_sanitize_self"), {"body": "<p>x</p>"})
        self.assertEqual(r.status_code, 403)

    # --- strip preview honors unsaved overrides + featured order -----------
    def test_strip_preview_lists_featured(self):
        _post(self.tenant, "Featured One", featured=True, order=0)
        r = self._tenant().get(reverse("dashboard:blog_strip_preview_self"))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "Featured One")

    def test_strip_preview_layout_override(self):
        _post(self.tenant, "F", featured=True, order=0)
        url = reverse("dashboard:blog_strip_preview_self")
        # Unsaved strip-layout choice is honored via the strip_style param.
        r = self._tenant().get(url + "?strip_style=overlay&heading=Reads&count=2")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "cms-strip--overlay")
        self.assertContains(r, "Reads")

    def test_strip_preview_all_layouts_render(self):
        _post(self.tenant, "Layout Post", featured=True, order=0)
        url = reverse("dashboard:blog_strip_preview_self")
        for layout in ("cards", "overlay", "spotlight", "list"):
            r = self._tenant().get(url + "?strip_style=" + layout)
            self.assertEqual(r.status_code, 200, layout)
            self.assertContains(r, "cms-strip--" + layout)
            self.assertContains(r, "Layout Post")

    def test_strip_style_saved_and_validated(self):
        c = self._tenant()
        c.post(reverse("dashboard:blog_settings_self"), {
            "template": "minimal", "strip_style": "spotlight",
            "title": "Blog", "strip_heading": "Latest", "strip_count": "3",
            "strip_enabled": "on",
        })
        self.tenant.refresh_from_db()
        self.assertEqual(self.tenant.blog_settings["strip_style"], "spotlight")
        # bogus layout falls back to the default
        c.post(reverse("dashboard:blog_settings_self"), {
            "template": "minimal", "strip_style": "nope",
            "title": "Blog", "strip_count": "3",
        })
        self.tenant.refresh_from_db()
        self.assertIn(self.tenant.blog_settings["strip_style"],
                      {"cards", "overlay", "spotlight", "list"})

    def test_strip_preview_disabled_message(self):
        _post(self.tenant, "F", featured=True, order=0)
        url = reverse("dashboard:blog_strip_preview_self")
        r = self._tenant().get(url + "?enabled=0")
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "turned off")

    def test_strip_preview_empty_state(self):
        r = self._tenant().get(reverse("dashboard:blog_strip_preview_self"))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, "No published featured posts")

    def test_strip_preview_excludes_drafts(self):
        _post(self.tenant, "DraftFeatured", status=BlogPost.STATUS_DRAFT, featured=True, order=0)
        r = self._tenant().get(reverse("dashboard:blog_strip_preview_self"))
        self.assertNotContains(r, "DraftFeatured")

    def test_strip_preview_auth_gated(self):
        c = Client(HTTP_HOST="acme.localhost")
        c.force_login(self.outsider)
        self.assertEqual(c.get(reverse("dashboard:blog_strip_preview_self")).status_code, 403)

    # --- end-to-end: the reported bug, through the real view flow ----------
    def test_strip_e2e_publish_feature_unfeature_unpublish_order(self):
        c = self._tenant()
        strip = reverse("dashboard:blog_strip_preview_self")

        # 1) Publish a post through the real form (no explicit publish_date —
        #    this is the path that previously left publish_date NULL).
        c.post(reverse("dashboard:blog_create_self"),
               {"title": "Alpha", "body": "<p>a</p>", "status": "published"})
        post = BlogPost.objects.get(tenant=self.tenant, title="Alpha")
        self.assertIsNotNone(post.publish_date)  # invariant holds

        # ...and feature it via the star toggle.
        c.post(reverse("dashboard:blog_featured_toggle_self", args=[post.pk]))
        r = c.get(strip)
        self.assertContains(r, "Alpha")            # (1) appears in the strip
        self.assertNotContains(r, "No published featured posts")

        # 2) Untoggle → disappears.
        c.post(reverse("dashboard:blog_featured_toggle_self", args=[post.pk]))
        self.assertNotContains(c.get(strip), "Alpha")

        # Re-feature for the unpublish check.
        c.post(reverse("dashboard:blog_featured_toggle_self", args=[post.pk]))
        self.assertContains(c.get(strip), "Alpha")

        # 3) Unpublish (back to draft) → disappears from the strip even though
        #    still featured (featured draft must NOT show publicly).
        c.post(reverse("dashboard:blog_edit_self", args=[post.pk]),
               {"title": "Alpha", "slug": post.slug, "body": "<p>a</p>",
                "status": "draft", "featured": "on"})
        post.refresh_from_db()
        self.assertTrue(post.featured)
        self.assertEqual(post.status, BlogPost.STATUS_DRAFT)
        self.assertNotContains(c.get(strip), "Alpha")

        # 4) Zero featured published posts → empty state shows.
        self.assertContains(c.get(strip), "No published featured posts")

        # 5) Ordering respects the manual featured_order.
        a = _post(self.tenant, "Order-A", featured=True, order=1)
        b = _post(self.tenant, "Order-B", featured=True, order=0)
        body = c.get(strip).content.decode()
        self.assertLess(body.index("Order-B"), body.index("Order-A"))  # order=0 first
